#import "../metadata.typ": *
#import "commun.typ": *
#import "letter/main.typ": *
#import "resume/section.typ": *
#import "resume/entry.typ": *
#import "resume/skills.typ": *
#import "resume/header.typ": *
#import "resume/footer.typ": *
#import "@preview/fontawesome:0.1.0": *
